image: node:10.15.0
pipelines:
  default:
    - step:
        script:
          - docker build -t betorobson/nodejsapp1:bitbucket-pipelines-v1-$BITBUCKET_COMMIT .
        services:
          - docker
    - step:
        script:
          - docker login -u betorobson -p Live9048
          - docker push betorobson/nodejsapp1:bitbucket-pipelines-v1-$BITBUCKET_COMMIT
        services:
          - docker