image: node:10.15.0
pipelines:
  default:
    - step:
        name: Build Docker image and Push to registry
        script:
          - IMAGE="${BITBUCKET_ACCOUNT}/nodejsapp1"
          - VERSION="latest branch-master build-number-commit.${BITBUCKET_BUILD_NUMBER}.${BITBUCKET_COMMIT}"
          - BUILD_NAME="${IMAGE}:${VERSION}"
          - echo "${BITBUCKET_PASSWORKD}" | docker login -u ${BITBUCKET_ACCOUNT} --password-stdin
          - echo "${BUILD_NAME}"
          - docker build -t ${BUILD_NAME} .
          - docker push ${BUILD_NAME}
        services:
          - docker
