image: node:10.15.0
pipelines:
  default:
    - step:
        name: Build Docker image and Push to registry
        script:
          - IMAGE="$DOCKERHUB_ACCOUNT/nodejsapp1"
          - VERSION="latest branch-master build-number-commit.${BITBUCKET_BUILD_NUMBER}.${BITBUCKET_COMMIT}"
          - BUILD_NAME="${IMAGE}:${VERSION}"
          - echo "${DOCKERHUB_PASSWORKD}" | docker login -u ${DOCKERHUB_ACCOUNT} --password-stdin
          # - echo $BUILD_NAME
          - docker build -t ${IMAGE}:bitbucket-pipelines-v6 .
          - docker push ${IMAGE}:bitbucket-pipelines-v6
        services:
          - docker
