image: node:10.15.0
pipelines:
  default:
    - step:
        script:
          - docker login -u betorobson -p live*3344
          - docker build -t betorobson/nodejsapp1:bitbucket-pipelines-v3 .
          - docker push betorobson/nodejsapp1:bitbucket-pipelines-v3
        services:
          - docker