image: node:10.15.0
pipelines:
  default:
    - step:
        script:
          - echo "${BITBUCKET_PASSWORKD}" | docker login -u ${BITBUCKET_ACCOUNT} --password-stdin
          - docker build -t betorobson/nodejsapp1:bitbucket-pipelines-v4-$BITBUCKET_COMMIT .
          - docker push betorobson/nodejsapp1:bitbucket-pipelines-v4-$BITBUCKET_COMMIT
        services:
          - docker