image: node:10.15.0
pipelines:
  branches:
    master:
      - step:
          name: Build Docker image production and Push to registry
          script:
            - IMAGE="$DOCKERHUB_ACCOUNT/nodejsapp1"
            - BUILD_TAGS_1="${IMAGE}:latest"
            - BUILD_TAGS_2="${IMAGE}:branch-${BITBUCKET_BRANCH}"
            - BUILD_TAGS_3="${IMAGE}:build-number-commit.${BITBUCKET_BUILD_NUMBER}.${BITBUCKET_COMMIT}"
            - BUILD_TAGS="-t ${BUILD_TAGS_1} -t ${BUILD_TAGS_2} -t ${BUILD_TAGS_3}"
            - echo "${DOCKERHUB_PASSWORKD}" | docker login -u ${DOCKERHUB_ACCOUNT} --password-stdin
            - docker build ${BUILD_TAGS} .
            - docker push ${BUILD_TAGS_1}
            - docker push ${BUILD_TAGS_2}
            - docker push ${BUILD_TAGS_3}
          services:
            - docker
    develop:
      - step:
          name: Build Docker image develop and Push to registry
          script:
            - NODE_APP_VERSION=$(node get-version.js)
            - IMAGE="$DOCKERHUB_ACCOUNT/nodejsapp1"
            - BUILD_TAGS_1="${IMAGE}:develop"
            - BUILD_TAGS_2="${IMAGE}:develop.${NODE_APP_VERSION}"
            - BUILD_TAGS_3="${IMAGE}:branch-${BITBUCKET_BRANCH}"
            - BUILD_TAGS_4="${IMAGE}:build-number-commit.${BITBUCKET_BUILD_NUMBER}.${BITBUCKET_COMMIT}"
            - BUILD_TAGS="-t ${BUILD_TAGS_1} -t ${BUILD_TAGS_2} -t ${BUILD_TAGS_3}"
            - echo "${DOCKERHUB_PASSWORKD}" | docker login -u ${DOCKERHUB_ACCOUNT} --password-stdin
            - docker build ${BUILD_TAGS} .
            - docker push ${BUILD_TAGS_1}
            - docker push ${BUILD_TAGS_2}
            - docker push ${BUILD_TAGS_3}
          services:
            - docker
