image: node:10.15.0
pipelines:
  default:
    - step:
        script:
          - docker build -t betorobson/nodejsapp1:bitbucket-pipelines-v1 .
        services:
          - docker
    - step:
        script:
          - docker login -u betorobson -p live*3344
          - docker push betorobson/nodejsapp1:bitbucket-pipelines-v1
        services:
          - docker