version: "3"

networks:
  isolation-network:
    driver: bridge

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.1
    # Enables the web UI and tells Traefik to listen to docker
    command:
     - --api.insecure=true
     - --providers.docker
     - --providers.docker.exposedbydefault=false
     - --entrypoints.web.address=:80
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  app1:
    build: .
    # ports:
    #   - "3000:3000"
    labels:
      # - traefik.http.routers.app1.rule=Host(`nodejsdeploy.betorobson`) || Host(`18.214.25.242`)
      - traefik.http.routers.app1.rule=Host(`localhost`) && PathPrefix(`/app1`)
      - traefik.enable=true
      - traefik.http.routers.app1.entrypoints=web

    command: yarn run start1

  app2:
    build: .
    # ports:
    #   - "3000:3000"
    labels:
      - traefik.http.routers.app2.rule=Host(`localhost`) && PathPrefix(`/app2`)
      - traefik.enable=true
      - traefik.http.routers.app2.entrypoints=web

    command: yarn run start2

  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    # ports:
    #   # The HTTP port
    #   - "3001:80"
    # labels:
      # - traefik.http.routers.whoami.rule=Host(`localhost`) && Path(`/whoami`)
      # - traefik.http.routers.whoami.rule=Host(`vaiplaneta.localhost`) || Host(`18.214.25.242`)
      # - traefik.enable=true
      # - traefik.http.routers.whoami.entrypoints=web
