version: "3"

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.1
    # Enables the web UI and tells Traefik to listen to docker
    command:
     - --api.insecure=true
     - --providers.docker
     - --providers.docker.exposedbydefault=false
     - --entrypoints.web.address=:80
     - --entrypoints.whoami.address=:3002
    ports:
      # The HTTP port
      - "80:80"
      - "3002:3002"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    build: .
    # ports:
    #   - "3000:3000"
    labels:
      - traefik.http.routers.app.rule=Host(`nodejsdeploy.betorobson`)
      - traefik.enable=true
      - traefik.http.routers.app.entrypoints=web

    command: yarn start

  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    # ports:
    #   # The HTTP port
    #   - "3001:80"
    labels:
      - traefik.http.routers.whoami.rule=Host(`vaiplaneta.localhost`)
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=whoami
